#! /bin/sh -
#
# SPDX-FileCopyrightText: 2026 Mateusz Piotrowski <0mp@FreeBSD.org>
# SPDX-License-Identifier: BSD-2-Clause
#

set -eu

back_up_file() {
	local _file="$1"
	local _realpath
	_realpath="$(realpath "$new")"
	printf '%s\n' "$_file" | pax -rw "$backup_dir"
}

usage() {
	cat << EOF
$0 [-h] [-d search_path ...]
-d search_path  Search the provided path for .pkgnew and .pkgsave files.
                The provided path cannot contain whitespace. The flag can be
                specified more than once. Default: "/".
-h              Show usage message.

XDG_CACHE_DIR   Directory for backup copies of processed files.
                Default: "${HOME}/.cache".
TMPDIR          Directory for temporary files. Default: "/tmp".
EOF
}

search_paths=""
backup_dir_template="${XDG_CACHE_DIR:-"${HOME}/.cache"}/$(date -Iseconds).XXXXX"
types="pkgnew pkgsave"

OPTIND=1
while getopts d:h opt; do
	case $opt in
	d)
		search_paths="${search_paths} ${OPTARG}"
		;;
	h)
		usage
		exit 0
		;;
	*)
		printf 'ERROR: Unknown option: %s' "$opt" >&2
		usage >&2
		exit 1
		;;
	esac
done
shift "$(( OPTIND - 1 ))"

if [ "$search_paths" = "" ]; then
	search_paths="/"
fi

for type in ${types}; do
	for new in $(find ${search_paths} -name "*${type}"); do
		old="${new%".${type}"}"
		merged="${new}.merged"

		if [ "${backup_dir:-}" = "" ]; then
			backup_dir="$(mktemp -d "${backup_dir_template}")"
		fi
		back_up_file "$old"
		back_up_file "$new"

		ok=false
		while [ "$ok" = false ]; do
			printf 'Merging into %s from %s:\n' "$old" "$new"
			if ! sdiff -o "$merged" "$old" "$new"; then
				if [ "$?" -gt 1 ]; then
					printf 'ERROR: Failed to merge into %s from %s\n' \
					    "$old" "$new" >&2
				fi
			fi
			while { [ "${MOCK_READ_YES:-}" = "true" ] && ok="y"; } ||
			    read -p "${old} merged? [yn] " ok
			do
				case $ok in
				[yY]*)
					ok="true"
					cp "$merged" "$old"
					rm "$new"
					rm "$merged"
					break
					;;
				esac
			done
		done

		case "$old" in
		/etc/master.passwd)
			pwd_mkdb -p /etc/master.passwd
			;;
		esac
	done
done
exit 0
